### ISSUE TITLE
Missing @using at Layout file

### ISSUE THREAD

**Issue by donhuvy** [aspnet/Scaffolding#1094]
## Steps to reproduce:
Please see https://stackoverflow.com/a/58204848/3728901

```
Severity:       Error
Error Code:     CS0246
Description:    The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)
Project:        foo
File:       C:\Users\donhuvy\Desktop\acc133b3\foo\obj\Debug\netcoreapp3.0\Razor\Pages\Shared\_Layout.cshtml.g.cs
Line:       455
Suppression State:  Active
```

## Expected behavior:

Has `@using ` at the top of file.

## Actual behavior:
Compile project error.

### Target framework(s):
.NET Core 3.0.100 , Visual Studio 2019

**Comment by donhuvy** [comment]
I am quite new to ASP.NET Core development (about 1.5 months). I confusing about Scaffolding for Blazor-server. The document (docs.microsoft.com) is also new, and often updated this time.

I try 2 different ways:

**First way:** I do like this: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#blazor-server-authentication . Then I want change default Identtiy UI, I need scaffoding. (A)

**Second way:** I run scaffolding step-by-step like this https://stackoverflow.com/a/58204848/3728901    (B)

I compare 2 layout file (A) and (B) are different, please explain for me.

How I scaffolding for authentication, authorization in right way with Blazor-server?

**Comment by donhuvy** [comment]
I confusing about Scaffolding authentication/authorization view files for Blazor-server. The document (docs.microsoft.com) is also new, and often updated this time.

I try 2 different ways:

**First way:** I do like this: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#blazor-server-authentication . Then I want change default Identtiy UI, I need scaffoding. (A)

**Second way:** I run scaffolding step-by-step like this https://stackoverflow.com/a/58204848/3728901    (B)

I compare 2 layout file (A) and (B) are different, please explain for me.

I have 2 type of layouts, I confused. File **MainLayout.razor** I get at here https://github.com/DevExpress/Blazor/blob/master/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/Shared/MainLayout.razor

![foo](https://user-images.githubusercontent.com/1328316/66067683-5109a900-e576-11e9-895d-363d0b8a61fd.png)


How I scaffolding for authentication, authorization in right way (good practice) with Blazor-server?

**Comment by vijayrkn** [comment]
@HaoK - This is already fixed right? If so, can you please resolve this bug?

**Comment by HaoK** [comment]
Fixed by https://github.com/aspnet/Scaffolding/pull/1043

**Comment by kanisimoff** [comment]
In .Net Core 3.1 I see same error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)	LogicServices	D:\GitHub\tyrchik\src\Tyrchik.Site\LogicLayer\LogicServices\UploadFileService.cs	15	Active

**Comment by vijayrkn** [comment]
@deepchoudhery can you please take a look?

**Comment by NetanelMosheCohen** [comment]
Any update for this issue? I'm still not able to use IWebHostEnvironment with .NET Core 3.1

**Comment by deepchoudhery** [comment]
The new packages for 3.1 should have the issue fixed. What is the version of the package being used currently?

**Comment by swidz** [comment]
In .Net 5 and ASP.NET Core 5 same error
The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?)

**Comment by dfdumaresq** [comment]
It's happening for me with 3.1.405

**Comment by AdnanZafar0005** [comment]
It is not working in .Net 5. Please fix it. I'm using @using Microsoft.AspNetCore.Hosting
