### ISSUE TITLE
Generated identity code fails to compile

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#731]
Repro steps:
- Create a new ASPNET Core Web Application
- Add a package reference to Microsoft.VisualStudio.Web.CodeGeneration.Design
- Right-click on the project and select "New Scaffolded Item..."
- Select the Identity scaffolder
- Leave layout blank, select "Override all files", create a new data context class, click OK
- Build the app

Expected result: App compiles and runs

Actual result: The type or namespace name 'ErrorModel' could not be found (are you missing a using directive or an assembly reference?)

Looks like `ErrorModel` in `Error.cshtml.cs` is in the wrong namespace. It should be in `WebApplication1.Areas.Identity.Pages` instead of `WebApplication1.Areas.Identity.Pages.Account`.

**Comment by danroth27** [comment]
@prafullbhosale @kichalla

**Comment by prafullbhosale** [comment]
cc @seancpeters

**Comment by seancpeters** [comment]
@danroth27 @prafullbhosale - I'm unable to repro this issue using the latest release/2.1 code (built locally), Possibly a problem with older bits?

In my project, the scaffolded Error.cshtml.cs includes:
```namespace WebApplication12.Areas.Identity.Pages.Account``` 
...but I have no build issues.

**Comment by seancpeters** [comment]
Ok, with the latest templates, I can repro this...fix coming soon.

**Comment by seancpeters** [comment]
Fixed by #753

**Comment by FiniteRealityTech** [comment]
I used the codegenerator on my .net core 2.2 project and I had the same issue. I changed the namespace of the class ErrorModel to MyWebSite.Areas.Identity.Pages.Account. However, on clean and build, the error persists: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ErrorModel' could not be found (are you missing a using directive or an assembly reference?)

Any advice?

**Comment by FiniteRealityTech** [comment]
By adding @using MyWebSite.Areas.Identity.Pages.Account to Error.cshtml fixed the issue.

**Comment by wildough57** [comment]
I'm seeing the same issue since I went from VS2019 16.4.0 preview 2.0 to preview 3.0.

**Comment by DotNetDublin** [comment]
Rain into this issue today and adding @using MyWebSite.Areas.Identity.Pages to Error.cshtml rather than MyWebSite.Areas.Identity.Pages.Account worked for me.

**Comment by Zalnlol** [comment]
> Rain into this issue today and adding @using MyWebSite.Areas.Identity.Pages to Error.cshtml rather than MyWebSite.Areas.Identity.Pages.Account worked for me.

Same, but each time i rerun compile, the line is removed and the same error pop up.
